CREATE TABLE ESTOQUE_LIVRO (
COD_LIVRO INT PRIMARY KEY NOT NULL, 
NOME_LIVRO VARCHAR (50) NOT NULL,
GENERO VARCHAR (50) NOT NULL,
PRECO MONEY NOT NULL )

INSERT INTO ESTOQUE_LIVRO VALUES (4,'CIDADES DE PAPEL','ROMANCE','23')

CREATE TABLE LIVRARIA (
COD_LIVRARIA INT PRIMARY KEY  NOT NULL,
NOME_LIVRARIA VARCHAR (50) NOT NULL,
EMAIL VARCHAR (100) NOT NULL,
ASSUNTO VARCHAR (100) NOT NULL)

CREATE TRIGGER INSERIR_ESTOQUE_LIVRO
ON ESTOQUE_LIVRO

FOR INSERT 
AS 
IF (SELECT COUNT(*) FROM INSERTED) = 1 
    PRINT 'NOVO LIVRO CADASTRADO COM SUCESSO!'

INSERT INTO ESTOQUE_LIVRO
(COD_LIVRO, NOME_LIVRO, GENERO, PRECO)
VALUES
(2,'HOBBIT','AVENTURA','25')
	

INSERT INTO ESTOQUE_LIVRO VALUES (3,'CIDADE DAS CINZAS- INSTRUMENTOS MORTAIS ','DRAMA/ROMANCE','23')
SELECT * FROM ESTOQUE_LIVRO


CREATE TRIGGER TRIGGER_LIVRARIA
  ON ESTOQUE_LIVRO 
FOR INSERT
  
AS 
  BEGIN
  DECLARE
    @COD_LIVRO INT ,
    @NOME_LIVRO VARCHAR (50);
  SELECT
    @COD_LIVRO = COD_LIVRO,
    @NOME_LIVRO = NOME_LIVRO
  FROM
    INSERTED
INSERT INTO LIVRARIA
(
NOME_LIVRARIA,
EMAIL,
ASSUNTO
)

VALUES
(
'SARAIVA',
'SARAIVA.CADASTRO@GMAIL.COM',
'FOI CADASTRADO UM NOVO LIVRO COM O CÓDIGO' + CAST ( @COD_LIVRO AS VARCHAR) + 'NOME_ALUNO' + @NOME_LIVRO
)
END

INSERT INTO ESTOQUE_LIVRO VALUES (5,'MELHOR DE MIM','ROMANCE','30')

SELECT*FROM LIVRARIA
SELECT*FROM ESTOQUE_LIVRO


CREATE PROCEDURE INSERIR_LIVRO 

@COD_LIVRO INT, 
@NOME_LIVRO VARCHAR (50),
@GENERO VARCHAR (50),
@PRECO MONEY 

AS
 BEGIN 
   INSERT INTO ESTOQUE_LIVRO

(
COD_LIVRO ,
NOME_LIVRO ,
GENERO ,
PRECO 
)
VALUES
(
@COD_LIVRO ,
@NOME_LIVRO ,
@GENERO ,
@PRECO 
)

 END

EXEC INSERIR_LIVRO 6,'THE VAMPIRE DIARES','AVENTURA/ROMANCE','29'
EXEC INSERIR_LIVRO 7,'A MENINA QUE ROUBAVA LIVRO','DRAMA','27'

SELECT*FROM ESTOQUE_LIVRO
SELECT*FROM LIVRARIA


CREATE TRIGGER ATUALIZAR_LIVRARIA
  ON ESTOQUE_LIVRO 
   FOR UPDATE 

AS 
 BEGIN
IF (SELECT COUNT(*)FROM DELETED)<> 0
    SELECT *FROM DELETED 
    SELECT *FROM INSERTED 
DECLARE 
    @COD_LIVRO INT ,
    @NOME_LIVRO VARCHAR (50);

    SELECT 
    @COD_LIVRO = COD_LIVRO,
    @NOME_LIVRO = NOME_LIVRO
     FROM
   INSERTED

INSERT INTO LIVRARIA
(
NOME_LIVRARIA,
EMAIL,
ASSUNTO
)
VALUES
(
'SARAIVA',
'UM CADASTRO DE LIVRO FOI ATUALIZADO',
'LIVRARIA SARAIVA,FOI ATUALIZADO UM CADASTRO DE LIVRO COM O CODIGO '
+ CAST ( @COD_LIVRO AS VARCHAR) + 'NOME_ALUNO' + @NOME_LIVRO
)
END

UPDATE ESTOQUE_LIVRO SET PRECO ='28' WHERE COD_LIVRO = 7
SELECT*FROM ESTOQUE_LIVRO


CREATE PROCEDURE ATUALIZAR_ESTOQUE
@COD_LIVRO INT, 
@NOME_LIVRO VARCHAR (50),
@GENERO VARCHAR (50),
@PRECO MONEY 

AS
BEGIN 
    UPDATE ESTOQUE_LIVRO
SET
NOME_LIVRO = @NOME_LIVRO,
@PRECO = @PRECO

WHERE
COD_LIVRO = @COD_LIVRO
END
     EXEC ATUALIZAR_ESTOQUE 1, 'CIDADE DE PAPEL','ROMANCE','25'
     EXEC ATUALIZAR_ESTOQUE 4, 'MEU PORTO SEGURO','ROMANCE','22'


CREATE  TRIGGER EXCLUIR_TRIGGER_AFTER
ON ESTOQUE_LIVRO

FOR DELETE
AS
  IF (SELECT COUNT (*) FROM DELETED) = 1 
       PRINT 'O LIVRO FOI EXLUIDO COM SUCESSO DO BANCO DE DADOS!!!!!'

DELETE FROM ESTOQUE_LIVRO WHERE NOME_LIVRO ='MEU PORTO SEGURO'
SELECT *FROM ESTOQUE_LIVRO



CREATE TRIGGER EXCLUIR_LIVRARIA
 ON ESTOQUE_LIVRO 
FOR DELETE 

AS 
 BEGIN 
  DECLARE 
   @COD_LIVRO INT ,
    @NOME_LIVRO VARCHAR (50);
     SELECT
    @COD_LIVRO = COD_LIVRO,
    @NOME_LIVRO = NOME_LIVRO

FROM
  DELETED
INSERT INTO LIVRARIA
(
NOME_LIVRARIA,
EMAIL,
ASSUNTO
)
VALUES
(
'SARAIVA',
'UM CADASTRO FOI DELETADO DO BANCO DE DADOS',
'FOI DELETADO UM CADASTRO DE LIVRO COM O CODIGO '
+ CAST ( @COD_LIVRO AS VARCHAR) + 'NOME_ALUNO ' + @NOME_LIVRO
)
END

DELETE ESTOQUE_LIVRO WHERE COD_LIVRO = 2

SELECT*FROM LIVRARIA
SELECT*FROM ESTOQUE_LIVRO

CREATE PROCEDURE EXCLUIR_LIVROS
   @COD_LIVRO INT

AS 
 BEGIN 
    DELETE
       FROM
    ESTOQUE_LIVRO
WHERE
 COD_LIVRO = @COD_LIVRO
END

EXEC EXCLUIR_LIVROS 3


SELECT*FROM ESTOQUE_LIVRO
SELECT*FROM LIVRARIA


CREATE PROCEDURE BUSCA_ESTOQUE
    @COD_LIVRO INT = NULL,
    @NOME_LIVRO VARCHAR (50)= NULL

AS
  BEGIN
SELECT
     *
      FROM
    ESTOQUE_LIVRO
WHERE
((COD_LIVRO = @COD_LIVRO) OR (@COD_LIVRO IS NULL))
AND
((NOME_LIVRO LIKE '%' + @NOME_LIVRO + '%') OR (@NOME_LIVRO IS NULL))
END

EXEC BUSCA_ESTOQUE 1
EXEC BUSCA_ESTOQUE NULL, 'MELHOR DE MIM'


CREATE PROCEDURE BUSCA_LIVRARIA
    @COD_LIVRARIA INT = NULL,
    @NOME_LIVRARIA VARCHAR (50)= NULL

AS
  BEGIN
SELECT
     *
      FROM
    LIVRARIA 
WHERE
((COD_LIVRARIA = @COD_LIVRARIA) OR (@COD_LIVRARIA IS NULL))
AND
((NOME_LIVRARIA LIKE '%' + @NOME_LIVRARIA + '%') OR (@NOME_LIVRARIA IS NULL))
END

EXEC BUSCA_LIVRARIA 1